DROP TABLE IF EXISTS `transactions_migrated`;
CREATE TABLE `transactions_migrated` (
  `row_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `invoice_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `reference_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `reference_row_id` bigint unsigned DEFAULT NULL COMMENT 'reference to parent transaction fatt.transaction.row_id',
  `recurring_transaction_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `auth_id` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `type` enum('charge','void','refund','capture','pre_auth','credit','') COLLATE utf8mb3_unicode_ci NOT NULL,
  `source` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL COMMENT 'The system where the payment was processed (e.g. terminalservice.dejavoo, haywire.apps). A value of null means that the transaction was processed within the Stax system via the core api.',
  `source_ip` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `is_merchant_present` tinyint(1) DEFAULT NULL,
  `merchant_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `user_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `customer_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `payment_method_id` varchar(40) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `is_manual` tinyint(1) DEFAULT NULL,
  `spreedly_token` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `spreedly_response` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `success` tinyint(1) NOT NULL,
  `message` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `meta` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `total` double NOT NULL,
  `method` varchar(20) COLLATE utf8mb3_unicode_ci NOT NULL,
  `pre_auth` tinyint(1) NOT NULL,
  `is_captured` tinyint(1) NOT NULL DEFAULT '0',
  `last_four` varchar(4) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `interchange_code` varchar(45) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `interchange_fee` double DEFAULT NULL,
  `batch_id` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `batched_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emv_response` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `avs_response` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `cvv_response` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `pos_entry` varchar(92) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `pos_salesperson` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `receipt_email_at` timestamp NULL DEFAULT NULL,
  `receipt_sms_at` timestamp NULL DEFAULT NULL,
  `settled_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `gateway_id` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `issuer_auth_code` varchar(50) COLLATE utf8mb3_unicode_ci GENERATED ALWAYS AS ((case when json_valid(`spreedly_response`) then coalesce(json_unquote(json_extract(`spreedly_response`,_utf8mb4'$.gateway_specific_response_fields.nmi.authcode')),json_unquote(json_extract(`spreedly_response`,_utf8mb4'$.gateway_specific_response_fields.forte.authorization_code')),json_unquote(json_extract(`spreedly_response`,_utf8mb4'$.gateway_specific_response_fields.authorize_net.authorization_code')),json_unquote(json_extract(`spreedly_response`,_utf8mb4'$.AuthCode'))) else _utf8mb4'' end)) STORED,
  `channel` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `currency` enum('USD','CAD','MXN','EUR','GBP') COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`created_at`, `row_id`),
  UNIQUE KEY `row_id_unique` (`row_id`),
  UNIQUE KEY `id_unique` (`id`),
  KEY `transactions_last_four_index` (`last_four`),
  KEY `transactions_reference_id_index` (`reference_id`),
  KEY `transactions_invoice_id_index` (`invoice_id`),
  KEY `transactions_auth_id_index` (`auth_id`),
  KEY `transactions_settled_at_index` (`settled_at`),
  KEY `transactions_customer_id_index` (`customer_id`),
  KEY `transactions_gateway_settled_at_index` (`gateway_id`,`settled_at`),
  KEY `transactions_ref_id_mid_index` (`reference_id`,`merchant_id`),
  KEY `transactions_merchant_id_issuer_auth_code_index` (`merchant_id`, `issuer_auth_code`),
  KEY `transactions_payment_method_id_index` (`payment_method_id`),
  KEY `transactions_source_created_at` (`source`,`created_at`),
  KEY `transactions_merchant_id` (merchant_id, success, type, method, created_at, customer_id, id, total)
) ENGINE=InnoDB AUTO_INCREMENT=100927564 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=COMPACT;
