drop table if exists mig_transactions_cdc;
create table mig_transactions_cdc
(
    row_id                   bigint                                                                 not null,
    id                       varchar(40)                                                            not null,
    invoice_id               varchar(40)                                                            not null,
    reference_id             varchar(40)                                                            not null,
    reference_row_id         bigint unsigned                                                        null comment 'reference to parent transaction fatt.transaction.row_id',
    recurring_transaction_id varchar(40)                                                            not null,
    auth_id                  varchar(50)                                                            null,
    type                     enum ('charge', 'void', 'refund', 'capture', 'pre_auth', 'credit', '') not null,
    source                   varchar(50)                                                            null comment 'The system where the payment was processed (e.g. terminalservice.dejavoo, haywire.apps). A value of null means that the transaction was processed within the Stax system via the core api.',
    source_ip                varchar(50)                                                            null,
    is_merchant_present      tinyint                                                                null,
    merchant_id              varchar(40)                                                            not null,
    user_id                  varchar(40)                                                            not null,
    customer_id              varchar(40)                                                            not null,
    payment_method_id        varchar(40)                                                            null,
    is_manual                tinyint                                                                null,
    spreedly_token           varchar(50)                                                            not null,
    spreedly_response        text                                                                   not null,
    success                  tinyint                                                                not null,
    message                  varchar(255)                                                           null,
    meta                     text                                                                   not null,
    total                    double                                                                 not null,
    method                   varchar(20)                                                            not null,
    pre_auth                 tinyint                                                                not null,
    is_captured              tinyint                                                                not null,
    last_four                varchar(4)                                                             null,
    interchange_code         varchar(45)                                                            null,
    interchange_fee          double                                                                 null,
    batch_id                 varchar(80)                                                            null,
    batched_at               timestamp                                                              null on update CURRENT_TIMESTAMP,
    emv_response             varchar(80)                                                            null,
    avs_response             varchar(80)                                                            null,
    cvv_response             varchar(80)                                                            null,
    pos_entry                varchar(92)                                                            null,
    pos_salesperson          varchar(80)                                                            null,
    receipt_email_at         timestamp                                                              null,
    receipt_sms_at           timestamp                                                              null,
    settled_at               timestamp                                                              null,
    year                     int                                                                    not null,
    month                    int                                                                    not null,
    created_at               timestamp                                                              not null,
    updated_at               timestamp                                                              not null,
    gateway_id               varchar(50)                                                            null,
    channel                  varchar(50)                                                            null,
    currency                 enum ('USD', 'CAD', 'MXN', 'EUR', 'GBP')                               null,
    cdc_type                 enum ('INSERT', 'UPDATE', 'DELETE') default 'INSERT'                   not null comment 'The type of change that occurred in the row.',
    cdc_created_at          timestamp   default CURRENT_TIMESTAMP                                  not null comment 'The timestamp of the change.'
);
