drop table if exists `mig_settlement_fees`;
create table `mig_settlement_fees` (
  `row_id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT 'PK',
  `id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `merchant_id` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `transaction_id` varchar(40) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `transaction_row_id` bigint unsigned DEFAULT NULL COMMENT 'processor.transaction.row_id',
  `batch_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `external_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `external_linked_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `source` enum('finix','reconciliation_engine','skynetsimulator','engine') CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `total` decimal(20,5) DEFAULT NULL,
  `type` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `subtype` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `name` varchar(30) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `settled_at` timestamp NULL DEFAULT NULL,
  `billing_invoice_id` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`created_at`, `row_id`),
  UNIQUE KEY `row_id_unique` (`row_id`),
  UNIQUE KEY `id_unique` (`id`),
  KEY `external_linked_id` (`external_linked_id`),
  KEY `fees_subtype_index` (`subtype`),
  KEY `batch_merchant_index` (`batch_id`,`merchant_id`),
  KEY `batch_created_at_index` (`batch_id`),
  KEY `transaction_id_merchant_id` (`transaction_id`,`merchant_id`),
  KEY `source_type_created_at` (`source`,`type`),
  KEY `merchant_id_index` (`merchant_id`)
) ENGINE=InnoDB AUTO_INCREMENT=153715873 DEFAULT CHARSET=utf8mb3 ROW_FORMAT=COMPACT;