drop table if exists mig_transactions;
create table `mig_transactions` (
  `row_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `invoice_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `reference_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `reference_row_id` bigint unsigned DEFAULT NULL COMMENT 'reference to parent transaction processor.transaction.row_id',
  `recurring_transaction_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `auth_id` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `type` enum('charge','void','refund','credit','debit','pre_auth','capture','','release','hold') COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `source` enum('emaf','finix','skynetsimulator','engine','test','') COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `source_ip` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `is_merchant_present` tinyint(1) DEFAULT NULL,
  `merchant_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `user_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `customer_id` varchar(40) COLLATE utf8mb3_unicode_ci NOT NULL,
  `payment_method_id` varchar(40) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `is_manual` tinyint(1) DEFAULT NULL,
  `spreedly_token` varchar(50) COLLATE utf8mb3_unicode_ci NOT NULL,
  `spreedly_response` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `success` tinyint(1) NOT NULL,
  `message` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `meta` text COLLATE utf8mb3_unicode_ci NOT NULL,
  `total` decimal(20,5) DEFAULT NULL,
  `method` enum('card','bank') COLLATE utf8mb3_unicode_ci NOT NULL,
  `pre_auth` tinyint(1) NOT NULL,
  `is_captured` tinyint(1) NOT NULL DEFAULT '0',
  `last_four` varchar(4) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `interchange_code` varchar(45) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `interchange_fee` double DEFAULT NULL,
  `batch_id` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `batched_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `emv_response` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `avs_response` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `cvv_response` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `pos_entry` varchar(92) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `pos_salesperson` varchar(80) COLLATE utf8mb3_unicode_ci DEFAULT '',
  `receipt_email_at` timestamp NULL DEFAULT NULL,
  `receipt_sms_at` timestamp NULL DEFAULT NULL,
  `settled_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT NULL,
  `gateway_id` varchar(40) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `issuer_auth_code` varchar(24) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `channel` varchar(50) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `is_reconciled` tinyint(1) DEFAULT NULL,
  `currency` enum('USD','CAD','MXN','EUR','GBP') COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`created_at`, `row_id`),
  UNIQUE KEY `id_unique` (`id`),
  UNIQUE KEY `row_id_unique` (`row_id`),
  KEY `transactions_merchant_settled_at` (`merchant_id`,`settled_at`),
  KEY `compound_ref_success_mid_created_at` (`reference_id`,`success`,`merchant_id`,`created_at`),
  KEY `transactions_merchant_batch_id_index` (`merchant_id`,`batch_id`),
  KEY `merchant_id_type` (`merchant_id`,`type`),
  KEY `is_reconciled_index` (`is_reconciled`),
  KEY `customer_id_reference_id` (`customer_id`,`reference_id`),
  KEY `reference_id_merchant_id_created_at` (`reference_id`,`merchant_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=589960155 DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci ROW_FORMAT=COMPACT;